curl 'URL_PREFIXFILE_NAME' \
  -H 'authority: caeducation.sharepoint.com' \
  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'cache-control: max-age=0' \
  -H 'cookie: REDACTED' \
  -H 'if-modified-since: REDACTED' \
  -H 'if-none-match: REDACTED' \
  -H 'referer: https://caeducation.sharepoint.com/sites/SBEPublicComments/Lists/SBE%20Public%20Comments/CommentsAtAGlance.aspx' \
  -H 'sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: REDACTED' \
  -H 'sec-fetch-dest: document' \
  -H 'sec-fetch-mode: navigate' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-user: ?1' \
  -H 'service-worker-navigation-preload: true' \
  -H 'upgrade-insecure-requests: 1' \
  -H 'user-agent: REDACTED' \
  --compressed \
  > attachments/ITEM_ID_FILE_NAME
